#################################
# Backend
#################################

backend = "glx";
vsync = true;

#################################
# Shadows
#################################

shadow = true;
shadow-radius = 12;
shadow-offset-x = -12;
shadow-offset-y = -12;
shadow-opacity = 0.30;

#################################
# Fading
#################################

fading = true;
fade-in-step = 0.04;
fade-out-step = 0.04;

#################################
# Transparency
#################################

frame-opacity = 0.9;
inactive-opacity = 0.95;
active-opacity = 1.0;

#################################
# Rounded Corners
#################################

corner-radius = 10;
detect-rounded-corners = true;

#################################
# Blur
#################################

blur-method = "dual_kawase";
blur-strength = 7;

blur-background = true;
blur-background-frame = true;
blur-background-fixed = false;

#################################
# General
#################################

detect-client-opacity = true;
detect-transient = true;
use-damage = true;

#################################
# Window Rules
#################################

rules: (
  {
    match = "window_type = 'dock' || window_type = 'desktop'";
    blur-background = false;
  },
  {
    match = "class_g = 'Conky'";
    shadow = false;
  }
)
