#! /bin/sh

# iniciar atalhos
pgrep -x sxhkd >/dev/null || sxhkd &

# configurar monitores
~/dotfiles/dualMonitor.sh
sleep 1
bspc wm -r

# dividir desktops
bspc monitor HDMI-0 -d 1 2 3 4 5
bspc monitor DVI-0 -d 6 7 8 9 10

# configuração visual
bspc config top_padding 24
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0

bspc config border_width 2
bspc config window_gap 12

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config focused_border_color "#ffffff"
bspc config normal_border_color "#444444"

# compositor
picom --config ~/.config/picom/picom.conf &

# wallpaper
~/.fehbg &

# polybar
~/.config/polybar/launch.sh &

# GARANTIR FOCO FINAL (ESSENCIAL)
sleep 1
bspc monitor HDMI-0 -f 1
bspc monitor DVI-0 -f 6
