#! /bin/sh

# 1. Iniciar atalhos (Essencial para o bspwm não "travar")
# Iniciar atalhos
if ! pgrep -x sxhkd >/dev/null; then
    sxhkd &
fi

# 2. Configurar monitores
# Alterado para o caminho do link criado pelo Stow
~/.config/bspwm/dualMonitor.sh

# 3. Dividir desktops (Workspaces)
# DICA: Se no Arch o nome mudar (ex: HDMI-A-1), você altera aquibspc monitor HDMI-A-0 -d 1 2 3 4 5
bspc monitor HDMI-A-0 -d 1 2 3 4 5 6 7 8 9 10

# 4. Configuração visual e Comportamento
bspc config top_padding 0
bspc config window_gap 5
bspc config border_width 2

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

# Cores (Branco para foco, Cinza para o resto)
bspc config focused_border_color "#fe8019"
bspc config normal_border_color "#2d2d2d"

# 5. Programas de Inicialização
pgrep -x picom >/dev/null || picom --config ~/.config/picom/picom.conf &

# Bloqueio automático após 10 minutos de inatividade
xset s 600
pgrep -x xss-lock >/dev/null || xss-lock -- i3lock -i "$HOME/.local/share/lockscreen/dual-lockscreen.png" &

# Wallpaper
sleep 1
[ -f ~/.fehbg ] && sh ~/.fehbg &

# Polybar
~/.config/polybar/launch.sh &

# 6. Foco Inicial

bspc monitor HDMI-A-0 -f 1
